service: put-in-sqs-from-s3-json
provider:
  name: aws
  runtime: python3.8
  region: us-east-1


  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "sqs:*"
      Resource: 
        - "arn:aws:sqs:us-east-1:*:*"


functions:
  put:
    handler: handler.handler
    environment:
      urlSQS: "https://sqs.us-east-1.amazonaws.com/764597347320/raw-json"
    events:
      - s3:
         bucket: bootcamp-fiap-rafael
         event: s3:ObjectCreated:*
         rules:
            - prefix: raw_json/
         existing: true